management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: '5'
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  application:
    name: grading-service
  boot:
    admin:
      client:
        url: http://localhost:9090
  datasource:
    password: '1234'
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5440/fyp_grading_db
